POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "dudoan",
    "password": "dukick0333vx"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "dudoan",
    "password": "dukick0333vx"
}